import { Geist } from "next/font/google";
import "@/app/globals.css";
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: 'MySQL CRUD with NextJS',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} antialiased`} >
        <Navbar />
        <main> {children} </main>
        <Footer />
      </body>
    </html>
  );
}
