import "@/app/globals.css";
import { Geist } from "next/font/google";
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: 'MySQL CRUD with NextJS',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} flex flex-col min-h-screen antialiased`} >
        <Navbar />
        <main className='grow p-4'> {children} </main>
        <Footer />
      </body>
    </html>
  );
}
